### ISSUE TITLE
Justify alignment in submission.md (if possible)

### ISSUE THREAD

**Issue by marigianna-iaas** [uniba-dsg/peace-ws#2]

**Comment by koppor** [comment]
Link: http://uniba-dsg.github.io/peace-ws/submission

Is the text too wide? The page had the same width as http://uniba-dsg.github.io/peace-ws/cfp. Should we change the width of all pages? I did that in a875b061d83c763bd69

Please force reload the page (ctrl+shift+r in Firefox), otherwise the header will look bad.

**Comment by marigianna-iaas** [comment]
in safari the text seems nice now

**Comment by lenhard** [comment]
To me the layout looks fine on all pages in Firefox. Much better than before!
